/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Duc Thao
 */
public class dangnhap22 extends javax.swing.JFrame {

    /**
     * Creates new form dangnhap22
     */
    public CardLayout card = new CardLayout();
    Connection cn;
    static String ROLE;
    static String USER;
    static String HOTEN;
    static String SDT;
    static String DIACHI;
    static String MAKH;

    public dangnhap22() {
        initComponents();
        Image();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Đăng Nhập - Hair Salon");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbllogin = new javax.swing.JLabel();
        lbSginup = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtTaiKhoan = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblbaosai = new javax.swing.JLabel();
        lblbaoloi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDangNhap1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 250, 290, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 110, 290, 20);

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel2.setText("LOGIN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 30, 150, 50);

        lbllogin.setFont(new java.awt.Font("Adobe Gothic Std B", 0, 18)); // NOI18N
        lbllogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Interface-Login-icon (1).png"))); // NOI18N
        lbllogin.setText("Login");
        lbllogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblloginMouseExited(evt);
            }
        });
        lbllogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblloginKeyReleased(evt);
            }
        });
        jPanel2.add(lbllogin);
        lbllogin.setBounds(110, 360, 120, 37);

        lbSginup.setFont(new java.awt.Font("Adobe Gothic Std B", 0, 18)); // NOI18N
        lbSginup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Interface-Login-icon (1).png"))); // NOI18N
        lbSginup.setText("Signup");
        lbSginup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSginupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSginupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSginupMouseExited(evt);
            }
        });
        lbSginup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbSginupKeyReleased(evt);
            }
        });
        jPanel2.add(lbSginup);
        lbSginup.setBounds(270, 360, 120, 37);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(0, 0, 570, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setAlignmentX(1.0F);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(60, 330, 390, 10);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(60, 190, 390, 10);

        txtTaiKhoan.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(102, 102, 102));
        txtTaiKhoan.setText("Nhap Username");
        txtTaiKhoan.setBorder(null);
        txtTaiKhoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTaiKhoanFocusGained(evt);
            }
        });
        jPanel2.add(txtTaiKhoan);
        txtTaiKhoan.setBounds(60, 150, 390, 40);

        txtPass.setForeground(new java.awt.Color(102, 102, 102));
        txtPass.setText("ádasdsadasdada");
        txtPass.setBorder(null);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
        });
        jPanel2.add(txtPass);
        txtPass.setBounds(60, 290, 390, 40);

        lblbaosai.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblbaosai);
        lblbaosai.setBounds(170, 110, 380, 20);

        lblbaoloi.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(lblbaoloi);
        lblbaoloi.setBounds(390, 150, 370, 0);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loginban.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 950, 470);

        btnDangNhap1.setBackground(new java.awt.Color(51, 0, 0));
        btnDangNhap1.setForeground(new java.awt.Color(255, 0, 0));
        btnDangNhap1.setText("ĐĂNG NHẬP");
        btnDangNhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhap1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDangNhap1);
        btnDangNhap1.setBounds(70, 300, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhap1ActionPerformed

    private void lblloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginMouseClicked
        // TODO add your handling code here:
        if (txtTaiKhoan.getText().equalsIgnoreCase("")) {
                lblbaosai.setText("Bạn chưa nhập tài khoản!");
                
            } else if (txtPass.getText().equalsIgnoreCase("")) {
                lblbaosai.setText("Bạn chưa nhập mật khẩu!");
                
            } else {
        try {
            PreparedStatement ps = cn.prepareStatement("select * from USES where USENAMES=? and PASSWORDS=?");
            ps.setString(1, txtTaiKhoan.getText());
            ps.setString(2, txtPass.getText());
            ResultSet rs = ps.executeQuery();

            //            PreparedStatement pss = cn.prepareStatement("SELECT * FROM USES LEFT OUTER JOIN KHACHHANG "
            //                    + "ON USES.USENAMES=KHACHHANG.USENAMES\n" + " WHERE USES.USENAMES=? AND KHACHHANG.USENAMES=?");
            //            pss.setString(1, txtTaiKhoan.getText());
            //            pss.setString(2, "IS NULL");
            //            ResultSet rss = pss.executeQuery();
            //            if (rss.next()) {
            //
            //                new NewJFrame().setVisible(true);
            ////                    new CapNhatThongTin().setVisible(true);
            
                if (rs.next()) {
                    try {
                        if (rs.getString(3).equalsIgnoreCase("KH")) {
                            USER = txtTaiKhoan.getText();
                            ROLE = rs.getString(3);
                            new GDchinh(USER, ROLE).setVisible(true);
                            this.dispose();

                        } else if (rs.getString(3).equalsIgnoreCase("ST")) {
                            USER = txtTaiKhoan.getText();
                            ROLE = rs.getString(3);
                            new GDchinh(USER, ROLE).setVisible(true);
                            this.dispose();
                            //                    new DangNhapFame(SDT, SDT, SDT, MAKH).dispose();
                        } else if (rs.getString(3).equalsIgnoreCase("NV")) {
                            USER = txtTaiKhoan.getText();
                            ROLE = rs.getString(3);
                            new GDchinh(USER, ROLE).setVisible(true);
                            this.dispose();
                            //                    new DangNhapFame(SDT, SDT, SDT, MAKH).dispose();
                        }

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    }

                } else {
                    lblbaosai.setText("Bạn đã nhập sai tài khoản hoặc mật khẩu");
                    
                }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
            }
    }//GEN-LAST:event_lblloginMouseClicked

    private void txtTaiKhoanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTaiKhoanFocusGained
        // TODO add your handling code here:
        txtTaiKhoan.setText("");
    }//GEN-LAST:event_txtTaiKhoanFocusGained

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        txtPass.setText("");
    }//GEN-LAST:event_txtPassFocusGained

    private void lblloginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblloginKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblloginKeyReleased

    private void lblloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginMouseEntered
        // TODO add your handling code here:
        lbllogin.setBackground(Color.green);
    }//GEN-LAST:event_lblloginMouseEntered

    private void lblloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginMouseExited
        // TODO add your handling code here:
        lbllogin.setBackground(Color.black);
    }//GEN-LAST:event_lblloginMouseExited

    private void lbSginupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSginupMouseClicked
        // TODO add your handling code here:
        new dangky22().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbSginupMouseClicked

    private void lbSginupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSginupMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSginupMouseEntered

    private void lbSginupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSginupMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSginupMouseExited

    private void lbSginupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbSginupKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSginupKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhap22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhap22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhap22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhap22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhap22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbSginup;
    private javax.swing.JLabel lblbaoloi;
    private javax.swing.JLabel lblbaosai;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void Image() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconhair.png")));
    }
}
