/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Duc Thao
 */
public class dangky22 extends javax.swing.JFrame {

    /**
     * Creates new form dangnhap22
     */
    public CardLayout card = new CardLayout();
    Connection cn;
    static String ROLE;
    static String USER;
    static String HOTEN;
    static String SDT;
    static String DIACHI;
    static String MAKH;
    public dangky22() {
        initComponents();
        Image();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Đăng Ký - Hair Salon");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblbaosai = new javax.swing.JLabel();
        cbbChonthang = new javax.swing.JComboBox<>();
        txtsodt = new javax.swing.JTextField();
        cbbChonnam = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        txtrePass = new javax.swing.JPasswordField();
        txtdiachi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txtuser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbSginup = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtHoten = new javax.swing.JTextField();
        cbbChonngay = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        lblbaosai.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(lblbaosai);
        lblbaosai.setBounds(0, 0, 0, 0);

        cbbChonthang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbbChonthang.setBorder(null);
        cbbChonthang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChonthangActionPerformed(evt);
            }
        });
        jPanel2.add(cbbChonthang);
        cbbChonthang.setBounds(400, 280, 50, 30);

        txtsodt.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtsodt.setBorder(null);
        jPanel2.add(txtsodt);
        txtsodt.setBounds(340, 170, 200, 40);

        cbbChonnam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003" }));
        cbbChonnam.setBorder(null);
        jPanel2.add(cbbChonnam);
        cbbChonnam.setBounds(460, 280, 60, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel6.setText("Number");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 140, 110, 17);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel9.setText("RE-PASSWORD");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 240, 160, 17);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(50, 410, 180, 10);

        txtPass.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setBorder(null);
        jPanel2.add(txtPass);
        txtPass.setBounds(50, 170, 190, 40);

        txtrePass.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtrePass.setForeground(new java.awt.Color(51, 51, 51));
        txtrePass.setBorder(null);
        jPanel2.add(txtrePass);
        txtrePass.setBounds(50, 270, 180, 40);

        txtdiachi.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtdiachi.setForeground(new java.awt.Color(51, 51, 51));
        txtdiachi.setBorder(null);
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        jPanel2.add(txtdiachi);
        txtdiachi.setBounds(50, 370, 180, 40);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 40, 100, 17);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 340, 100, 17);

        Txtuser.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        Txtuser.setForeground(new java.awt.Color(51, 51, 51));
        Txtuser.setBorder(null);
        jPanel2.add(Txtuser);
        Txtuser.setBounds(50, 70, 190, 40);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel8.setText("Email");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(340, 340, 60, 17);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(50, 210, 180, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 140, 100, 17);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel4.setText("Full Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 40, 90, 17);

        lbSginup.setFont(new java.awt.Font("Adobe Gothic Std B", 0, 18)); // NOI18N
        lbSginup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User-Interface-Login-icon (1).png"))); // NOI18N
        lbSginup.setText("Signup");
        lbSginup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSginupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbSginupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbSginupMouseExited(evt);
            }
        });
        lbSginup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbSginupKeyReleased(evt);
            }
        });
        jPanel2.add(lbSginup);
        lbSginup.setBounds(220, 430, 120, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/door-icon.png"))); // NOI18N
        jLabel2.setText("Quay lai");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 430, 80, 32);

        txtemail.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtemail.setForeground(new java.awt.Color(51, 51, 51));
        txtemail.setBorder(null);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel2.add(txtemail);
        txtemail.setBounds(340, 370, 200, 40);
        jPanel2.add(jSeparator8);
        jSeparator8.setBounds(340, 410, 200, 10);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(340, 210, 200, 10);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(50, 310, 180, 20);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(340, 110, 200, 20);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(50, 110, 180, 20);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 0, 570, 20);

        txtHoten.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        txtHoten.setBorder(null);
        jPanel2.add(txtHoten);
        txtHoten.setBounds(340, 70, 200, 40);

        cbbChonngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        cbbChonngay.setBorder(null);
        jPanel2.add(cbbChonngay);
        cbbChonngay.setBounds(340, 280, 50, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel11.setText("Birth Day");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(340, 240, 90, 17);

        jLabel5.setBackground(new java.awt.Color(51, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loginban.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 950, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbChonthangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChonthangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbChonthangActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void lbSginupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSginupMouseClicked
        // TODO add your handling code here:
         if (!txtrePass.getText().equalsIgnoreCase(txtPass.getText())) {
//            lblrepass.setText("Hai mật khẩu không giống nhau!");
        } else {

            
            try {
                PreparedStatement ps = cn.prepareStatement("INSERT INTO USES\n"
                    + "VALUES (?,?,?)   \n"
                    + "INSERT INTO KHACHHANG\n"
                    + "VALUES (?,?,?,?,?,?) ");
                ps.setString(1, Txtuser.getText());
                ps.setString(2, txtPass.getText());
                ps.setString(3, "KH");
                ps.setString(4, Txtuser.getText());
                ps.setString(5, txtHoten.getText());
                ps.setString(6, cbbChonnam.getSelectedItem() + "-" + cbbChonthang.getSelectedItem() + "-" + cbbChonngay.getSelectedItem());
                ps.setString(7, txtsodt.getText());
                ps.setString(8, txtdiachi.getText());
                ps.setString(9, txtemail.getText());

                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(this, "BẠN ĐÃ ĐĂNG KÝ THÀNH CÔNG!");
                    new dangnhap22().setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_lbSginupMouseClicked

    private void lbSginupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSginupMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSginupMouseEntered

    private void lbSginupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSginupMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSginupMouseExited

    private void lbSginupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbSginupKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSginupKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
        new dangnhap22().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangky22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangky22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangky22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangky22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangky22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtuser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbChonnam;
    private javax.swing.JComboBox<String> cbbChonngay;
    private javax.swing.JComboBox<String> cbbChonthang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbSginup;
    private javax.swing.JLabel lblbaosai;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtrePass;
    private javax.swing.JTextField txtsodt;
    // End of variables declaration//GEN-END:variables

    private void Image() {
setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconhair.png")));    }
}
