/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JComboBox;

import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Duc Thao
 */
public class DatLich extends javax.swing.JPanel {

    Connection cn;
    String DATE;
    String USERST;
    String ROLE;
    String USER;
    String EMAIL;
    String HOTEN;
    String SDT;
    String DIACHI;
    String NAMSINH;
    String MADV;
    String MACS;
    String MANV;
    String GIO;
    String TONGTIEN;
    String cbb;
    Calendar cal = Calendar.getInstance();
    String m = String.valueOf(cal.get(Calendar.MONTH) + 1);
    String y = String.valueOf(cal.get(Calendar.YEAR));
    int homNay, ngayMai, ngayKia;
    String n1 = "";
    int d = cal.get(Calendar.HOUR_OF_DAY);

    public DatLich(String user, String role) {
        initComponents();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        USER = user;
        ROLE = role;

        try {
            PreparedStatement ps = cn.prepareStatement("SELECT HOTEN,NAMSINH,SODT,DIACHI,EMAIL FROM KHACHHANG WHERE USENAMES=?");
            ps.setString(1, USER);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                HOTEN = rs.getString(1);
                NAMSINH = rs.getString(2);
                DIACHI = rs.getString(4);
                SDT = rs.getString(3);
                EMAIL = rs.getString(5);
            }
        } catch (Exception e) {
        }

//        
//        SDT = sdt;
//        DIACHI = dc;
//        MAKH = mkh;
//        btnS1.setVisible(false);
//        btnS2.setVisible(false);
//        btnS3.setVisible(false);
//        cbbChonngay.addItem(LocalDate.now());
        loadCBBNgay();
        loadCBBDICHVU();
        loadCBBNgay();
        lblnam.setText(y);
        lblthang.setText(m);
//        System.out.println(cbbChonNgay.getSelectedItem());
        lblngay.setText("0");
        lblHoTenDatLich.setText(HOTEN);
        lblTenKH.setText(HOTEN);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblHoTenDatLich = new javax.swing.JLabel();
        btnXaDan = new javax.swing.JButton();
        btnLangHa = new javax.swing.JButton();
        btnCauGiay = new javax.swing.JButton();
        cbbDichVu = new javax.swing.JComboBox<>();
        cbbStylelist = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn7h = new javax.swing.JButton();
        btn8h = new javax.swing.JButton();
        btn9h = new javax.swing.JButton();
        btn10h = new javax.swing.JButton();
        btn14h = new javax.swing.JButton();
        btn15h = new javax.swing.JButton();
        btn16h = new javax.swing.JButton();
        btn17h = new javax.swing.JButton();
        btn18h = new javax.swing.JButton();
        btnNgay1 = new javax.swing.JButton();
        btnNgay2 = new javax.swing.JButton();
        btnNgay3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCoSo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblngay = new javax.swing.JLabel();
        lblthang = new javax.swing.JLabel();
        lblnam = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblGioCat = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTGDuKien = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbltt = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(197, 225, 165));

        jPanel1.setBackground(new java.awt.Color(197, 225, 165));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("HỌ TÊN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CHỌN CƠ SỞ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CHỌN STYLE LIST");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CHỌN GIỜ");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        lblHoTenDatLich.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHoTenDatLich.setForeground(new java.awt.Color(255, 255, 255));
        lblHoTenDatLich.setText("HỌ TÊN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHoTenDatLich, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoTenDatLich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnXaDan.setBackground(new java.awt.Color(204, 0, 0));
        btnXaDan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXaDan.setForeground(new java.awt.Color(255, 255, 255));
        btnXaDan.setText("Xã Đàn");
        btnXaDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXaDanActionPerformed(evt);
            }
        });

        btnLangHa.setBackground(new java.awt.Color(204, 0, 0));
        btnLangHa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLangHa.setForeground(new java.awt.Color(255, 255, 255));
        btnLangHa.setText("Láng Hạ");
        btnLangHa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLangHaActionPerformed(evt);
            }
        });

        btnCauGiay.setBackground(new java.awt.Color(204, 0, 0));
        btnCauGiay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCauGiay.setForeground(new java.awt.Color(255, 255, 255));
        btnCauGiay.setText("Cầu Giấy");
        btnCauGiay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauGiayActionPerformed(evt);
            }
        });

        cbbDichVu.setBackground(new java.awt.Color(102, 204, 0));
        cbbDichVu.setForeground(new java.awt.Color(204, 0, 0));
        cbbDichVu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbDichVuItemStateChanged(evt);
            }
        });
        cbbDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDichVuActionPerformed(evt);
            }
        });

        cbbStylelist.setBackground(new java.awt.Color(102, 204, 0));
        cbbStylelist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbStylelistItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CHỌN NGÀY");

        jPanel4.setBackground(new java.awt.Color(197, 225, 165));

        btn7h.setBackground(java.awt.Color.green);
        btn7h.setText("07:00");
        btn7h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7hActionPerformed(evt);
            }
        });

        btn8h.setBackground(java.awt.Color.green);
        btn8h.setText("08:00");
        btn8h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8hActionPerformed(evt);
            }
        });

        btn9h.setBackground(java.awt.Color.green);
        btn9h.setText("09:00");
        btn9h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9hActionPerformed(evt);
            }
        });

        btn10h.setBackground(java.awt.Color.green);
        btn10h.setText("10:00");
        btn10h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10hActionPerformed(evt);
            }
        });

        btn14h.setBackground(java.awt.Color.green);
        btn14h.setText("14:00");
        btn14h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14hActionPerformed(evt);
            }
        });

        btn15h.setBackground(java.awt.Color.green);
        btn15h.setText("15:00");
        btn15h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15hActionPerformed(evt);
            }
        });

        btn16h.setBackground(java.awt.Color.green);
        btn16h.setText("16:00");
        btn16h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16hActionPerformed(evt);
            }
        });

        btn17h.setBackground(java.awt.Color.green);
        btn17h.setText("17:00");
        btn17h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17hActionPerformed(evt);
            }
        });

        btn18h.setBackground(java.awt.Color.green);
        btn18h.setText("18:00");
        btn18h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18hActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn7h, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn8h, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn9h, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn10h, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn14h, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn15h, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn16h, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn17h, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn18h, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7h, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8h, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9h, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn10h, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14h, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn15h, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn16h, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17h, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn18h, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnNgay1.setBackground(java.awt.Color.blue);
        btnNgay1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNgay1.setForeground(new java.awt.Color(255, 255, 255));
        btnNgay1.setText("jButton1");
        btnNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgay1ActionPerformed(evt);
            }
        });

        btnNgay2.setBackground(java.awt.Color.blue);
        btnNgay2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNgay2.setForeground(new java.awt.Color(255, 255, 255));
        btnNgay2.setText("jButton2");
        btnNgay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgay2ActionPerformed(evt);
            }
        });

        btnNgay3.setBackground(java.awt.Color.blue);
        btnNgay3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNgay3.setForeground(new java.awt.Color(255, 255, 255));
        btnNgay3.setText("jButton3");
        btnNgay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgay3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CHỌN DỊCH VỤ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbStylelist, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnXaDan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(btnLangHa)
                            .addGap(30, 30, 30)
                            .addComponent(btnCauGiay)
                            .addGap(30, 30, 30)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNgay3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXaDan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLangHa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCauGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbStylelist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNgay3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(100, 100, 100))))
        );

        jPanel2.setBackground(new java.awt.Color(197, 225, 165));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(197, 225, 165));

        jLabel14.setBackground(new java.awt.Color(255, 0, 102));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("HÓA ĐƠN");

        jLabel8.setText("Tên Khách:");

        lblTenKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenKH.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setText("Dịch Vụ:");

        lblDichVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setText("Cơ Sở:");

        lblCoSo.setBackground(new java.awt.Color(197, 225, 165));
        lblCoSo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCoSo.setForeground(new java.awt.Color(255, 0, 0));

        jLabel11.setText("Style List:");

        lblSL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSL.setForeground(new java.awt.Color(255, 0, 0));

        jLabel18.setText("Ngày Cắt:");

        lblngay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblngay.setForeground(new java.awt.Color(255, 0, 0));
        lblngay.setText("Ngay");

        lblthang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblthang.setForeground(new java.awt.Color(255, 0, 0));
        lblthang.setText("Thang");

        lblnam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblnam.setForeground(new java.awt.Color(255, 0, 0));
        lblnam.setText("Nam");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("/");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("/");

        jLabel12.setText("Giờ Cắt:");

        lblGioCat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGioCat.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setText("Thời Gian Dự Kiến:");

        lblTGDuKien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTGDuKien.setForeground(new java.awt.Color(255, 0, 0));

        jLabel15.setText("Tổng Tiền:");

        lbltt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltt.setForeground(new java.awt.Color(255, 0, 0));

        btnXacNhan.setBackground(new java.awt.Color(255, 153, 153));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác Nhận Đặt Lịch");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnXacNhan)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblngay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblthang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblnam))
                                    .addComponent(lblGioCat, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTGDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSL, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblSL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblngay)
                    .addComponent(lblthang)
                    .addComponent(lblnam)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblGioCat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblTGDuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lbltt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnXacNhan))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐẶT LỊCH CẮT TÓC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        hoaDon();
        new DatLich(USER, ROLE).setVisible(true);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void cbbDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDichVuActionPerformed

    private void cbbDichVuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbDichVuItemStateChanged
        lblDichVu.setText((String) cbbDichVu.getSelectedItem());
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT TENDV, THOIGIANDK, GIA, MADV FROM DICHVU where TENDV like ?");
            ps.setString(1, String.valueOf(cbbDichVu.getSelectedItem()));
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                lblTGDuKien.setText(String.valueOf(rs.getFloat(2)));
                lbltt.setText(String.valueOf(rs.getDouble(3)));
                MADV = rs.getString(1);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbbDichVuItemStateChanged

    private void btnXaDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXaDanActionPerformed

        if (n1.equalsIgnoreCase("")) {
            n1 = String.valueOf(ngayMai);
        } else if (n1.equalsIgnoreCase(String.valueOf(homNay))) {
            n1 = String.valueOf(homNay);
        } else {
            n1 = String.valueOf(ngayMai);
        }
        LoadTimeFILL();
        btnXaDan.setBackground(Color.GRAY);
        btnLangHa.setBackground(Color.RED);
        btnCauGiay.setBackground(Color.RED);
        MACS = "CS1";

        cbbStylelist.removeAllItems();
        try {
            Statement stm = cn.createStatement();

            ResultSet rs = stm.executeQuery("SELECT HOTEN FROM STYLELIST WHERE MACS LIKE 'CS1'");

            while (rs.next()) {
                cbbStylelist.addItem(rs.getString(1));

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        lblSL.setText(cbbStylelist.getSelectedItem().toString());
        lblCoSo.setText("Xã Đàn");
//        btnS1.setVisible(true);
//        btnS2.setVisible(true);
//        btnS3.setVisible(true);
//        btnS1.setText("Quốc Quân");
//        btnS2.setText("Anh Đức");
//        btnS3.setText("Tiến Anh");
    }//GEN-LAST:event_btnXaDanActionPerformed

    private void btn15hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn15h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GRAY);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn15hActionPerformed

    private void btnLangHaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLangHaActionPerformed
        // TODO add your handling code here:
        btnXaDan.setBackground(Color.RED);
        btnLangHa.setBackground(Color.GRAY);
        btnCauGiay.setBackground(Color.RED);
        if (n1.equalsIgnoreCase("")) {
            n1 = String.valueOf(ngayMai);
        } else if (n1.equalsIgnoreCase(String.valueOf(homNay))) {
            n1 = String.valueOf(homNay);
        } else {
            n1 = String.valueOf(ngayMai);
        }
        LoadTimeFILL();
        lblSL.setText("");

        MACS = "CS2";
        cbbStylelist.removeAllItems();
        try {
            Statement stm = cn.createStatement();

            ResultSet rs = stm.executeQuery("SELECT HOTEN FROM STYLELIST WHERE MACS LIKE 'CS2'");

            while (rs.next()) {
                cbbStylelist.addItem(rs.getString(1));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        lblSL.setText(cbbStylelist.getSelectedItem().toString());
        lblCoSo.setText("LÁNG HẠ");
//        btnS1.setVisible(true);
//        btnS2.setVisible(true);
//        btnS3.setVisible(true);
//        btnS1.setText("Linh Anh");
//        btnS2.setText("Phùng Đại");
//        btnS3.setText("Nguyễn Duy");
    }//GEN-LAST:event_btnLangHaActionPerformed

    private void btnCauGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCauGiayActionPerformed
        // TODO add your handling code here:
        btnXaDan.setBackground(Color.RED);
        btnLangHa.setBackground(Color.RED);
        btnCauGiay.setBackground(Color.GRAY);

        if (n1.equalsIgnoreCase("")) {
            n1 = String.valueOf(ngayMai);
        } else if (n1.equalsIgnoreCase(String.valueOf(homNay))) {
            n1 = String.valueOf(homNay);
        } else {
            n1 = String.valueOf(ngayMai);
        }
        LoadTimeFILL();
        lblSL.setText("");

        MACS = "CS3";
        cbbStylelist.removeAllItems();
        try {
            Statement stm = cn.createStatement();

            ResultSet rs = stm.executeQuery("SELECT HOTEN FROM STYLELIST WHERE MACS LIKE 'CS3'");

            while (rs.next()) {
                cbbStylelist.addItem(rs.getString(1));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        lblSL.setText(cbbStylelist.getSelectedItem().toString());
        lblCoSo.setText("Cầu Giấy");
//        btnS1.setVisible(true);
//        btnS2.setVisible(true);
//        btnS3.setVisible(true);
//        btnS1.setText("Trần Quyết");
//        btnS2.setText("Đại Nghĩa");
//        btnS3.setText("Phan Anh");
    }//GEN-LAST:event_btnCauGiayActionPerformed

    private void btn7hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn7h.getText());
        btn7h.setBackground(Color.GRAY);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);

    }//GEN-LAST:event_btn7hActionPerformed

    private void btn8hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn8h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GRAY);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn8hActionPerformed

    private void btn9hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn9h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GRAY);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn9hActionPerformed

    private void btn10hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn10h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GRAY);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn10hActionPerformed

    private void btn14hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn14h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GRAY);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn14hActionPerformed

    private void btn16hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn16h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GRAY);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn16hActionPerformed

    private void btn17hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn17h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GRAY);
        btn18h.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn17hActionPerformed

    private void btn18hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18hActionPerformed
        // TODO add your handling code here:
        lblGioCat.setText(btn18h.getText());
        btn7h.setBackground(Color.GREEN);
        btn8h.setBackground(Color.GREEN);
        btn9h.setBackground(Color.GREEN);
        btn10h.setBackground(Color.GREEN);
        btn14h.setBackground(Color.GREEN);
        btn15h.setBackground(Color.GREEN);
        btn16h.setBackground(Color.GREEN);
        btn17h.setBackground(Color.GREEN);
        btn18h.setBackground(Color.GRAY);
    }//GEN-LAST:event_btn18hActionPerformed

    private void cbbStylelistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbStylelistItemStateChanged
        // TODO add your handling code here:
//        LoadTime();
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT USENAMES, HOTEN FROM STYLELIST WHERE HOTEN=?");
            ps.setString(1, cbbStylelist.getSelectedItem().toString());

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                USERST = rs.getString(1);
                LoadTimeFILL();
                lblSL.setText(cbbStylelist.getSelectedItem().toString());

            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_cbbStylelistItemStateChanged

    private void btnNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgay1ActionPerformed
        try {
            n1 = String.valueOf(homNay);
            btnNgay1.setBackground(Color.GRAY);
            btnNgay2.setBackground(Color.BLUE);
            btnNgay3.setBackground(Color.BLUE);
            cbb = String.valueOf(homNay);
            lblngay.setText(cbb);
            DATE = cbb + "-" + m + "-" + y;
            LoadTimeFILL();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnNgay1ActionPerformed

    private void btnNgay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgay2ActionPerformed
        try {
            n1 = String.valueOf(ngayMai);
            btnNgay1.setBackground(Color.BLUE);
            btnNgay2.setBackground(Color.GRAY);
            btnNgay3.setBackground(Color.BLUE);
            cbb = String.valueOf(ngayMai);
            lblngay.setText(cbb);
            DATE = cbb + "-" + m + "-" + y;
            LoadTimeFILL();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnNgay2ActionPerformed

    private void btnNgay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgay3ActionPerformed
        try {
            n1 = String.valueOf(ngayKia);
            btnNgay1.setBackground(Color.BLUE);
            btnNgay2.setBackground(Color.BLUE);
            btnNgay3.setBackground(Color.GRAY);
            cbb = String.valueOf(ngayKia);
            lblngay.setText(cbb);
            DATE = cbb + "-" + m + "-" + y;
            LoadTimeFILL();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnNgay3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10h;
    private javax.swing.JButton btn14h;
    private javax.swing.JButton btn15h;
    private javax.swing.JButton btn16h;
    private javax.swing.JButton btn17h;
    private javax.swing.JButton btn18h;
    private javax.swing.JButton btn7h;
    private javax.swing.JButton btn8h;
    private javax.swing.JButton btn9h;
    private javax.swing.JButton btnCauGiay;
    private javax.swing.JButton btnLangHa;
    private javax.swing.JButton btnNgay1;
    private javax.swing.JButton btnNgay2;
    private javax.swing.JButton btnNgay3;
    private javax.swing.JButton btnXaDan;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbbDichVu;
    private javax.swing.JComboBox<String> cbbStylelist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCoSo;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblGioCat;
    private javax.swing.JLabel lblHoTenDatLich;
    private javax.swing.JLabel lblSL;
    private javax.swing.JLabel lblTGDuKien;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblnam;
    private javax.swing.JLabel lblngay;
    private javax.swing.JLabel lblthang;
    private javax.swing.JLabel lbltt;
    // End of variables declaration//GEN-END:variables

    private void loadCBBDICHVU() {
        try {
            Statement stm = cn.createStatement();
            ResultSet rs = stm.executeQuery("select TENDV,THOIGIANDK,GIA from DICHVU ");
            while (rs.next()) {
                cbbDichVu.addItem(rs.getString(1));
                lblTGDuKien.setText(String.valueOf(rs.getFloat(2)));
                lbltt.setText(String.valueOf(rs.getDouble(3)));

            }
        } catch (Exception e) {
        }
    }

    private void hoaDon() {
        int i = 0;
        if (lblCoSo.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn Cơ Sở!");
            return;
        } else if (lblSL.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn StyleList!");
            return;
        } else if (lblGioCat.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn giờ cắt!");
            return;
        } else if (lblngay.getText().equalsIgnoreCase("0")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn Ngày cắt!");
            return;
        } else {

            try {
                PreparedStatement psm = cn.prepareStatement("SELECT * FROM DATLICH WHERE USENAMES=? AND STATUSS=?");
                psm.setString(1, USER);
                psm.setString(2, "Chưa Hoàn Thành");

                ResultSet rs = psm.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Bạn đang có lịch chờ! hãy hoàn thành nó!");
                } else {

                    PreparedStatement ps = cn.prepareStatement("INSERT INTO DATLICH "
                            + "VALUES (?,?,?,?,?,?,?,?)");
                    ps.setString(1, USER);
                    ps.setString(2, MADV);
                    ps.setString(3, MACS);
                    ps.setString(4, USERST);
                    ps.setString(5, lblGioCat.getText());
                    ps.setString(6, DATE);
                    ps.setString(7, lbltt.getText());
                    ps.setString(8, "Chưa Hoàn Thành");

                    if (ps.executeUpdate() > 0) {
                        PreparedStatement pss = cn.prepareStatement("INSERT INTO GIOCAT\n"
                                + "VALUES (?,?,?,?,?)");
                        pss.setString(1, USER);
                        pss.setString(2, USERST);
                        pss.setString(3, lblGioCat.getText());
                        pss.setString(4, DATE);
                        pss.setString(5, EMAIL);

                        if (pss.executeUpdate() > 0) {

                            JOptionPane.showMessageDialog(this, "Bạn đạt lịch thành công");
                            //send email
                            final String username = "ducthao.isme@gmail.com";
                            final String password = "nguyenducthao";

                            Properties prop = new Properties();
                            prop.put("mail.smtp.host", "smtp.gmail.com");
                            prop.put("mail.smtp.port", "587");
                            prop.put("mail.smtp.auth", "true");
                            prop.put("mail.smtp.starttls.enable", "true"); //TLS

                            Session session = Session.getInstance(prop,
                                    new javax.mail.Authenticator() {
                                protected PasswordAuthentication getPasswordAuthentication() {
                                    return new PasswordAuthentication(username, password);
                                }
                            });

                            try {

                                Message message = new MimeMessage(session);
                                message.setFrom(new InternetAddress("ducthao.isme@gmail.com"));
                                message.setRecipients(
                                        Message.RecipientType.TO,
                                        InternetAddress.parse(EMAIL)
                                );
                                message.setSubject("ĐẶT LỊCH CẮT TÓC THÀNH CÔNG!");

                                message.setText("SALON HAIR - XIN CẢM ƠN BẠN ĐÃ SỬ DỤNG DỊCH VỤ CỦA CHÚNG TÔI! \n"
                                        +"Thông tin đặt lịch\n"
                                        + "\nKhách hàng:                    " + HOTEN + "\n"
                                        + "\nSố Điện Thoại:                 " + SDT + "\n"
                                        + "\nCơ sở:                         " + lblCoSo.getText() + "\n"
                                        + "\nDịch vụ:                       " + MADV + "\n"
                                        + "\nStyle List:                    " + USERST + "\n"
                                        + "\nGiờ cắt:                       " + lblGioCat.getText() + "\n"
                                        + "\nNgày cắt:                      " + lblngay.getText() + "-" + lblthang.getText() + "-" + lblnam.getText() + "\n"
                                        + "\nTổng Tiền:                     " + lbltt.getText() + "\n"
                                        + "\nMời quý khách hàng đến lúc " + lblGioCat.getText() + " Giờ"
                                        + " ngày " + lblngay.getText() + "-" + lblthang.getText() + "-" + lblnam.getText() + " "
                                        + "Tại cơ sở " + lblCoSo.getText() + " để sự dụng dịch vụ \n"
                                        + "Xin cảm ơn quý khách!");

                                Transport.send(message);

                                JOptionPane.showMessageDialog(this, "Email done!");

                            } catch (MessagingException e) {
                                JOptionPane.showMessageDialog(this, e);
                            }

                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Bạn không đặt lich thành công!:)))");
                    }
                    LoadTimeFILL();
                }
//                if (i == 1) {
//                    
//
//                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Đã bị lỗi gì đó! Hãy liên hệ với Admin!");
            }
        }
//        }
    }

    private void LoadTimeFILL() {
        String sql = "DECLARE @DATE NVARCHAR(20),\n"
                + "		@GIO NVARCHAR(20),\n"
                + "		@USENAMES NVARCHAR(20);\n"
                + "  \n"
                + "SET @USENAMES = ?;\n"
                + "SET	@GIO = ?;\n"
                + "SET	@DATE = ?;\n"
                + "  \n"
                + "SELECT\n"
                + "    USENAMESst,\n"
                + "    GIO,\n"
                + "    NGAY\n"
                + "FROM\n"
                + "    GIOCAT\n"
                + "WHERE\n"
                + "    NGAY = @DATE AND\n"
                + "	GIO = @GIO AND\n"
                + "	USENAMESst = @USENAMES";
        try {
            PreparedStatement ps1 = cn.prepareStatement(sql);
            ps1.setString(1, USERST);
            ps1.setString(2, "07:00");
            ps1.setString(3, DATE);
            ResultSet rs1 = ps1.executeQuery();
            if (rs1.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 7) {
                btn7h.setEnabled(false);
//                lblGioCat.setText(btn7h.getText());
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn7h.setEnabled(true);
            }

            PreparedStatement ps2 = cn.prepareStatement(sql);
            ps2.setString(1, USERST);
            ps2.setString(2, "08:00");
            ps2.setString(3, DATE);
            ResultSet rs2 = ps2.executeQuery();
            if (rs2.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 8) {
                btn8h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn8h.setEnabled(true);
            }

            PreparedStatement ps3 = cn.prepareStatement(sql);
            ps3.setString(1, USERST);
            ps3.setString(2, "09:00");
            ps3.setString(3, DATE);
            ResultSet rs3 = ps3.executeQuery();
            if (rs3.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 9) {
                btn9h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn9h.setEnabled(true);
            }

            PreparedStatement ps4 = cn.prepareStatement(sql);
            ps4.setString(1, USERST);
            ps4.setString(2, "10:00");
            ps4.setString(3, DATE);
            ResultSet rs4 = ps4.executeQuery();
            if (rs4.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 10) {
                btn10h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn10h.setEnabled(true);
            }

            PreparedStatement ps5 = cn.prepareStatement(sql);
            ps5.setString(1, USERST);
            ps5.setString(2, "14:00");
            ps5.setString(3, DATE);
            ResultSet rs5 = ps5.executeQuery();
            if (rs5.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 14) {
                btn14h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn14h.setEnabled(true);
            }

            PreparedStatement ps6 = cn.prepareStatement(sql);
            ps6.setString(1, USERST);
            ps6.setString(2, "15:00");
            ps6.setString(3, DATE);
            ResultSet rs6 = ps6.executeQuery();
            if (rs6.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 15) {
                btn15h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn15h.setEnabled(true);
            }

            PreparedStatement ps7 = cn.prepareStatement(sql);
            ps7.setString(1, USERST);
            ps7.setString(2, "16:00");
            ps7.setString(3, DATE);
            ResultSet rs7 = ps7.executeQuery();
            if (rs7.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 16) {
                btn16h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn16h.setEnabled(true);
            }

            PreparedStatement ps8 = cn.prepareStatement(sql);
            ps8.setString(1, USERST);
            ps8.setString(2, "17:00");
            ps8.setString(3, DATE);
            ResultSet rs8 = ps8.executeQuery();
            if (rs8.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 17) {
                btn17h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn17h.setEnabled(true);
            }

            PreparedStatement ps9 = cn.prepareStatement(sql);
            ps9.setString(1, USERST);
            ps9.setString(2, "18:00");
            ps9.setString(3, DATE);
            ResultSet rs9 = ps9.executeQuery();
            if (rs9.next() || n1.equalsIgnoreCase(String.valueOf(homNay)) && d >= 18) {
                btn18h.setEnabled(false);
                btn7h.setBackground(Color.GREEN);
                btn8h.setBackground(Color.GREEN);
                btn9h.setBackground(Color.GREEN);
                btn10h.setBackground(Color.GREEN);
                btn14h.setBackground(Color.GREEN);
                btn15h.setBackground(Color.GREEN);
                btn16h.setBackground(Color.GREEN);
                btn17h.setBackground(Color.GREEN);
                btn18h.setBackground(Color.GREEN);
            } else {
                btn18h.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

//    private void LoadCBBST() {
//
//        try {
//            PreparedStatement ps = cn.prepareStatement("SELECT HOTEN FROM STYLELIST WHERE MACS=?");
//            ps.setString(1, MACS);
//
//            ResultSet rs = ps.executeQuery();
//            while (rs.next()) {
//                cbbStylelist.addItem(rs.getString(1));
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e);
//        }
//
//    }
    private void loadCBBNgay() {
        try {
            homNay = cal.get(Calendar.DAY_OF_MONTH);
            btnNgay1.setText(String.valueOf(homNay + "/Tháng " + m));
            ngayMai = homNay + 1;
            btnNgay2.setText(String.valueOf(ngayMai + "/Tháng " + m));
            ngayKia = ngayMai + 1;
            btnNgay3.setText(String.valueOf(ngayKia + "/Tháng " + m));
//            lblthangcat.setText(m);
//            lblnamcat.setText(y);
            cbb = String.valueOf(homNay);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
}
