/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Duc Thao
 */
public class GDchinh extends javax.swing.JFrame {

    public CardLayout card = new CardLayout();
    Connection cn;
    static String ROLE;
    static String USER;
    static String HOTEN;
    static String SDT;
    static String DIACHI;
    static String MAKH;

    public GDchinh(String user, String role) {

        initComponents();
        setLocationRelativeTo(null);
        setTitle("Phần Mềm Đặt Lịch Cắt Tóc SALON HAIR");
        pnMain.setLayout(card);
        setResizable(false);
        Images();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        USER = user;
        ROLE = role;

        if (ROLE.equalsIgnoreCase("KH")) {
            jpDanhsachdatlich.setVisible(false);
            jpLichstylelist.setVisible(false);

        }else if(ROLE.equalsIgnoreCase("ST")){
            jpDatlichcattoc.setBackground(Color.gray);
            jpLíchucattoc.setBackground(Color.gray);
            jpDanhsachdatlich.setBackground(Color.gray);
        }else if(ROLE.equalsIgnoreCase("NV")){
            jpDatlichcattoc.setBackground(Color.gray);
            jpLíchucattoc.setBackground(Color.gray);
            jpLichstylelist.setBackground(Color.gray);
        }
//        HOTEN = ht;
//        SDT = sdt;
//        DIACHI = dc;
//        MAKH = mkh;

    }

    /**
     * Creates new form GDchinh
     */
    /**
     * Form This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jpThongtincanhan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpLíchucattoc = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpDatlichcattoc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpKieutochot2020 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpStylelist = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpLichstylelist = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpDanhsachdatlich = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(197, 225, 165));
        pnMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(211, 47, 47));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU - SALON");

        jPanel4.setBackground(new java.awt.Color(73, 89, 154));

        jpThongtincanhan.setBackground(new java.awt.Color(51, 138, 62));
        jpThongtincanhan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpThongtincanhanFocusGained(evt);
            }
        });
        jpThongtincanhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpThongtincanhanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpThongtincanhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpThongtincanhanMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpThongtincanhanMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/person-icon (1).png"))); // NOI18N
        jLabel1.setText("THÔNG TIN CÁ NHÂN");

        javax.swing.GroupLayout jpThongtincanhanLayout = new javax.swing.GroupLayout(jpThongtincanhan);
        jpThongtincanhan.setLayout(jpThongtincanhanLayout);
        jpThongtincanhanLayout.setHorizontalGroup(
            jpThongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongtincanhanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpThongtincanhanLayout.setVerticalGroup(
            jpThongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpThongtincanhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpLíchucattoc.setBackground(new java.awt.Color(51, 138, 62));
        jpLíchucattoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLíchucattocMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/ModernXP-43-Date-New-icon.png"))); // NOI18N
        jLabel4.setText("LỊCH SỬ CẮT TÓC");

        javax.swing.GroupLayout jpLíchucattocLayout = new javax.swing.GroupLayout(jpLíchucattoc);
        jpLíchucattoc.setLayout(jpLíchucattocLayout);
        jpLíchucattocLayout.setHorizontalGroup(
            jpLíchucattocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLíchucattocLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpLíchucattocLayout.setVerticalGroup(
            jpLíchucattocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLíchucattocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpDatlichcattoc.setBackground(new java.awt.Color(51, 138, 62));
        jpDatlichcattoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDatlichcattocMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/gnome-calendar-icon.png"))); // NOI18N
        jLabel3.setText("ĐẶT LỊCH CẮT TÓC");

        javax.swing.GroupLayout jpDatlichcattocLayout = new javax.swing.GroupLayout(jpDatlichcattoc);
        jpDatlichcattoc.setLayout(jpDatlichcattocLayout);
        jpDatlichcattocLayout.setHorizontalGroup(
            jpDatlichcattocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatlichcattocLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpDatlichcattocLayout.setVerticalGroup(
            jpDatlichcattocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatlichcattocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpKieutochot2020.setBackground(new java.awt.Color(51, 138, 62));
        jpKieutochot2020.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpKieutochot2020MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/Male-icon.png"))); // NOI18N
        jLabel5.setText("KIỂU TÓC HOT 2020");

        javax.swing.GroupLayout jpKieutochot2020Layout = new javax.swing.GroupLayout(jpKieutochot2020);
        jpKieutochot2020.setLayout(jpKieutochot2020Layout);
        jpKieutochot2020Layout.setHorizontalGroup(
            jpKieutochot2020Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKieutochot2020Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpKieutochot2020Layout.setVerticalGroup(
            jpKieutochot2020Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpKieutochot2020Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpStylelist.setBackground(new java.awt.Color(51, 138, 62));
        jpStylelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpStylelistMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/Man-9-icon.png"))); // NOI18N
        jLabel6.setText("STYLE LIST");

        javax.swing.GroupLayout jpStylelistLayout = new javax.swing.GroupLayout(jpStylelist);
        jpStylelist.setLayout(jpStylelistLayout);
        jpStylelistLayout.setHorizontalGroup(
            jpStylelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStylelistLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpStylelistLayout.setVerticalGroup(
            jpStylelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpStylelistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpLichstylelist.setBackground(new java.awt.Color(51, 138, 62));
        jpLichstylelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLichstylelistMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/Google-Calendar-icon.png"))); // NOI18N
        jLabel7.setText("LỊCH STYLE LIST");

        javax.swing.GroupLayout jpLichstylelistLayout = new javax.swing.GroupLayout(jpLichstylelist);
        jpLichstylelist.setLayout(jpLichstylelistLayout);
        jpLichstylelistLayout.setHorizontalGroup(
            jpLichstylelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLichstylelistLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpLichstylelistLayout.setVerticalGroup(
            jpLichstylelistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLichstylelistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpDanhsachdatlich.setBackground(new java.awt.Color(51, 138, 62));
        jpDanhsachdatlich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpDanhsachdatlichMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java/man-icon.png"))); // NOI18N
        jLabel8.setText("DANH SÁCH ĐẶT LỊCH");

        javax.swing.GroupLayout jpDanhsachdatlichLayout = new javax.swing.GroupLayout(jpDanhsachdatlich);
        jpDanhsachdatlich.setLayout(jpDanhsachdatlichLayout);
        jpDanhsachdatlichLayout.setHorizontalGroup(
            jpDanhsachdatlichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDanhsachdatlichLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpDanhsachdatlichLayout.setVerticalGroup(
            jpDanhsachdatlichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDanhsachdatlichLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("UVN Gia Dinh", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apps-session-logout-icon.png"))); // NOI18N
        jLabel9.setText("Đăng xuất");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpThongtincanhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpLíchucattoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDatlichcattoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpKieutochot2020, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpStylelist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpLichstylelist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDanhsachdatlich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jpThongtincanhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDatlichcattoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLíchucattoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpKieutochot2020, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpStylelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLichstylelist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDanhsachdatlich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpThongtincanhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpThongtincanhanMouseClicked
        // TODO add your handling code here:

        pnMain.add(new ThongTinCaNhan(USER, ROLE), "ttcn");
        card.show(pnMain, "ttcn");
        jpThongtincanhan.setBackground(new Color(197, 202, 233));
        jpDatlichcattoc.setBackground(new Color(51, 138, 62));
        jpDanhsachdatlich.setBackground(new Color(51, 138, 62));
        jpKieutochot2020.setBackground(new Color(51, 138, 62));
        jpLichstylelist.setBackground(new Color(51, 138, 62));
        jpStylelist.setBackground(new Color(51, 138, 62));
        jpLíchucattoc.setBackground(new Color(51, 138, 62));
    }//GEN-LAST:event_jpThongtincanhanMouseClicked

    private void jpDatlichcattocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDatlichcattocMouseClicked
        // TODO add your handling code here:
        if (ROLE.equalsIgnoreCase("NV")) {
            jpDatlichcattoc.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else if (ROLE.equalsIgnoreCase("ST")) {
            jpDatlichcattoc.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            pnMain.add(new DatLich(USER, ROLE), "dl");
            card.show(pnMain, "dl");
            jpThongtincanhan.setBackground(new Color(51, 138, 62));
            jpDatlichcattoc.setBackground(new Color(197, 202, 233));
            jpDanhsachdatlich.setBackground(new Color(51, 138, 62));
            jpKieutochot2020.setBackground(new Color(51, 138, 62));
            jpLichstylelist.setBackground(new Color(51, 138, 62));
            jpStylelist.setBackground(new Color(51, 138, 62));
            jpLíchucattoc.setBackground(new Color(51, 138, 62));
        }
    }//GEN-LAST:event_jpDatlichcattocMouseClicked

    private void jpLíchucattocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLíchucattocMouseClicked
        // TODO add your handling code here:
        if (ROLE.equalsIgnoreCase("NV")) {
            jpLíchucattoc.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else if (ROLE.equalsIgnoreCase("ST")) {
            jpLíchucattoc.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            pnMain.add(new LichSuCatToc(USER), "lsct");
            card.show(pnMain, "lsct");
            jpThongtincanhan.setBackground(new Color(51, 138, 62));
            jpDatlichcattoc.setBackground(new Color(51, 138, 62));
            jpDanhsachdatlich.setBackground(new Color(51, 138, 62));
            jpKieutochot2020.setBackground(new Color(51, 138, 62));
            jpLichstylelist.setBackground(new Color(51, 138, 62));
            jpStylelist.setBackground(new Color(51, 138, 62));
            jpLíchucattoc.setBackground(new Color(197, 202, 233));
        }
    }//GEN-LAST:event_jpLíchucattocMouseClicked

    private void jpKieutochot2020MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpKieutochot2020MouseClicked
        // TODO add your handling code here:
        pnMain.add(new KieuToc(), "kt");
        card.show(pnMain, "kt");
        jpThongtincanhan.setBackground(new Color(51, 138, 62));
        jpDatlichcattoc.setBackground(new Color(51, 138, 62));
        jpDanhsachdatlich.setBackground(new Color(51, 138, 62));
        jpKieutochot2020.setBackground(new Color(197, 202, 233));
        jpLichstylelist.setBackground(new Color(51, 138, 62));
        jpStylelist.setBackground(new Color(51, 138, 62));
        jpLíchucattoc.setBackground(new Color(51, 138, 62));
    }//GEN-LAST:event_jpKieutochot2020MouseClicked

    private void jpStylelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpStylelistMouseClicked
        // TODO add your handling code here:

        pnMain.add(new StyleList(), "st");
        card.show(pnMain, "st");
        jpThongtincanhan.setBackground(new Color(51, 138, 62));
        jpDatlichcattoc.setBackground(new Color(51, 138, 62));
        jpDanhsachdatlich.setBackground(new Color(51, 138, 62));
        jpKieutochot2020.setBackground(new Color(51, 138, 62));
        jpLichstylelist.setBackground(new Color(51, 138, 62));
        jpStylelist.setBackground(new Color(197, 202, 233));
        jpLíchucattoc.setBackground(new Color(51, 138, 62));
    }//GEN-LAST:event_jpStylelistMouseClicked

    private void jpLichstylelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLichstylelistMouseClicked
        // TODO add your handling code here:
        if (ROLE.equalsIgnoreCase("NV")) {
            jpLichstylelist.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            pnMain.add(new LichStyleList(USER), "dsl");
            card.show(pnMain, "dsl");
            jpThongtincanhan.setBackground(new Color(51, 138, 62));
            jpDatlichcattoc.setBackground(new Color(51, 138, 62));
            jpDanhsachdatlich.setBackground(new Color(51, 138, 62));
            jpKieutochot2020.setBackground(new Color(51, 138, 62));
            jpLichstylelist.setBackground(new Color(197, 202, 233));
            jpStylelist.setBackground(new Color(51, 138, 62));
            jpLíchucattoc.setBackground(new Color(51, 138, 62));
        }
    }//GEN-LAST:event_jpLichstylelistMouseClicked

    private void jpDanhsachdatlichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDanhsachdatlichMouseClicked
        // TODO add your handling code here:
        if (ROLE.equalsIgnoreCase("ST")) {
            jpDanhsachdatlich.setBackground(Color.gray);
            JOptionPane.showMessageDialog(this, "Bạn không có quyền truy cập!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            pnMain.add(new DanhSachDatLich(), "dsdl");
            card.show(pnMain, "dsdl");
            jpThongtincanhan.setBackground(new Color(51, 138, 62));
            jpDatlichcattoc.setBackground(new Color(51, 138, 62));
            jpDanhsachdatlich.setBackground(new Color(197, 202, 233));
            jpKieutochot2020.setBackground(new Color(51, 138, 62));
            jpLichstylelist.setBackground(new Color(51, 138, 62));
            jpStylelist.setBackground(new Color(51, 138, 62));
            jpLíchucattoc.setBackground(new Color(51, 138, 62));
        }
    }//GEN-LAST:event_jpDanhsachdatlichMouseClicked

    private void jpThongtincanhanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpThongtincanhanFocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jpThongtincanhanFocusGained

    private void jpThongtincanhanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpThongtincanhanMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jpThongtincanhanMouseReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        int e = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất?", "Đăng Xuất", JOptionPane.YES_OPTION);
        if(e==JOptionPane.YES_OPTION){
            new dangnhap22().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jpThongtincanhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpThongtincanhanMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jpThongtincanhanMouseEntered

    private void jpThongtincanhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpThongtincanhanMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jpThongtincanhanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GDchinh(USER, ROLE).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpDanhsachdatlich;
    private javax.swing.JPanel jpDatlichcattoc;
    private javax.swing.JPanel jpKieutochot2020;
    private javax.swing.JPanel jpLichstylelist;
    private javax.swing.JPanel jpLíchucattoc;
    private javax.swing.JPanel jpStylelist;
    private javax.swing.JPanel jpThongtincanhan;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables

    private void Images() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconhair.png")));
    }
}
