/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duc Thao
 */
public class LichSuCatToc extends javax.swing.JPanel {

    /**
     * Creates new form LichSuCatToc
     */
    DefaultTableModel model;
    Connection cn;
    String USER;

    public LichSuCatToc(String U) {
        initComponents();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        USER = U;
        model = (DefaultTableModel) jTable1.getModel();
        
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(197,225,165));
        jTable1.getTableHeader().setForeground(new Color(221, 44, 0));
        jTable1.setRowHeight(25);
        jTable1.setBackground(new Color(197,225,165));
        
        model.setColumnIdentifiers(new Object[]{"Cơ Sở", "Style List", "Dịch Vụ", "Giờ Cắt", "Ngày Cắt", "Tổng Tiền","Trạng Thái"});
        loadCbb();
        loadToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbb = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(197, 225, 165));

        jTable1.setBackground(new java.awt.Color(197, 225, 165));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LỊCH SỬ CẮT TÓC");

        jPanel1.setBackground(new java.awt.Color(197, 225, 165));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BỘ LỌC"));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));

        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn ngày" }));
        cbb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cbb, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbItemStateChanged
        
        try {
             model.setRowCount(0);
                PreparedStatement ps = cn.prepareStatement("SELECT COSO.DIACHI,STYLELIST.HOTEN,TENDV,GIO,NGAY,TONGTIEN,STATUSS FROM KHACHHANG INNER JOIN DATLICH ON\n"
                        + "KHACHHANG.USENAMES=DATLICH.USENAMES INNER JOIN STYLELIST ON\n"
                        + "DATLICH.USENAMEST=STYLELIST.USENAMES INNER JOIN COSO ON\n"
                        + "STYLELIST.MACS=COSO.MACS WHERE KHACHHANG.USENAMES=? AND NGAY=?");
                ps.setString(1, USER);
                ps.setString(2, String.valueOf(cbb.getSelectedItem()));
                
                
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getFloat(6),rs.getString(7)});
                }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbbItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void loadCbb() {
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT NGAY FROM KHACHHANG INNER JOIN DATLICH ON\n"
                    + "KHACHHANG.USENAMES=DATLICH.USENAMES INNER JOIN STYLELIST ON\n"
                    + "DATLICH.USENAMEST=STYLELIST.USENAMES INNER JOIN COSO ON\n"
                    + "STYLELIST.MACS=COSO.MACS WHERE KHACHHANG.USENAMES=?");
            ps.setString(1, USER);
            

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cbb.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }

    }

    private void loadToTable() {
        try {
             model.setRowCount(0);
                PreparedStatement ps = cn.prepareStatement("SELECT COSO.DIACHI,STYLELIST.HOTEN,TENDV,GIO,NGAY,TONGTIEN,STATUSS FROM KHACHHANG INNER JOIN DATLICH ON\n"
                        + "KHACHHANG.USENAMES=DATLICH.USENAMES INNER JOIN STYLELIST ON\n"
                        + "DATLICH.USENAMEST=STYLELIST.USENAMES INNER JOIN COSO ON\n"
                        + "STYLELIST.MACS=COSO.MACS WHERE KHACHHANG.USENAMES=?");
                ps.setString(1, USER);
                
                
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5),rs.getFloat(6),rs.getString(7)});
                }

        } catch (Exception e) {
        }

    }
}
