/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatTocP2;

import Conn.MyConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Nguyen Duc Thao
 */
public class ThongTinCaNhan extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    String u, r;
    Connection cn;

    public ThongTinCaNhan(String USER, String ROLE) {
        initComponents();
        cn = MyConnect.ketnoi("DATLICH_HAIRS");
        u = USER;
        r = ROLE;
//        lblmkc.setVisible(false);
//        txtnhappasscu.setVisible(false);
//        btnok.setVisible(false);
        fillTT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNGAYSINH = new javax.swing.JPanel();
        txtNGSINH = new javax.swing.JLabel();
        txtHOTEN = new javax.swing.JPanel();
        txtTEN = new javax.swing.JLabel();
        txtTENDANGNHAP = new javax.swing.JPanel();
        txtUSE = new javax.swing.JLabel();
        txtSODT = new javax.swing.JPanel();
        txtSDT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDIACHI = new javax.swing.JPanel();
        txtDCHI = new javax.swing.JLabel();
        txtGIOITINH = new javax.swing.JPanel();
        txtGT = new javax.swing.JLabel();
        txtDOIPASSS = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(197, 225, 165));

        jPanel1.setBackground(new java.awt.Color(197, 225, 165));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("TÊN ĐĂNG NHẬP: ");

        jLabel3.setText("HỌ VÀ TÊN:");

        jLabel4.setText("NGÀY SINH:");

        jLabel5.setText("SỐ ĐT:");

        txtNGAYSINH.setBackground(new java.awt.Color(204, 204, 204));

        txtNGSINH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNGSINH.setText("jLabel8");

        javax.swing.GroupLayout txtNGAYSINHLayout = new javax.swing.GroupLayout(txtNGAYSINH);
        txtNGAYSINH.setLayout(txtNGAYSINHLayout);
        txtNGAYSINHLayout.setHorizontalGroup(
            txtNGAYSINHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNGAYSINHLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtNGSINH, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtNGAYSINHLayout.setVerticalGroup(
            txtNGAYSINHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNGAYSINHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNGSINH, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        txtHOTEN.setBackground(new java.awt.Color(204, 204, 204));

        txtTEN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTEN.setText("jLabel8");

        javax.swing.GroupLayout txtHOTENLayout = new javax.swing.GroupLayout(txtHOTEN);
        txtHOTEN.setLayout(txtHOTENLayout);
        txtHOTENLayout.setHorizontalGroup(
            txtHOTENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtHOTENLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtTEN, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtHOTENLayout.setVerticalGroup(
            txtHOTENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtHOTENLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTEN, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        txtTENDANGNHAP.setBackground(new java.awt.Color(204, 204, 204));

        txtUSE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUSE.setText("jLabel8");

        javax.swing.GroupLayout txtTENDANGNHAPLayout = new javax.swing.GroupLayout(txtTENDANGNHAP);
        txtTENDANGNHAP.setLayout(txtTENDANGNHAPLayout);
        txtTENDANGNHAPLayout.setHorizontalGroup(
            txtTENDANGNHAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtTENDANGNHAPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtUSE, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtTENDANGNHAPLayout.setVerticalGroup(
            txtTENDANGNHAPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtTENDANGNHAPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUSE, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        txtSODT.setBackground(new java.awt.Color(204, 204, 204));

        txtSDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSDT.setText("jLabel8");

        javax.swing.GroupLayout txtSODTLayout = new javax.swing.GroupLayout(txtSODT);
        txtSODT.setLayout(txtSODTLayout);
        txtSODTLayout.setHorizontalGroup(
            txtSODTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtSODTLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtSODTLayout.setVerticalGroup(
            txtSODTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtSODTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jLabel6.setText("ĐỊA CHỈ:");

        jLabel7.setText("GIỚI TÍNH:");

        txtDIACHI.setBackground(new java.awt.Color(204, 204, 204));

        txtDCHI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDCHI.setText("jLabel8");

        javax.swing.GroupLayout txtDIACHILayout = new javax.swing.GroupLayout(txtDIACHI);
        txtDIACHI.setLayout(txtDIACHILayout);
        txtDIACHILayout.setHorizontalGroup(
            txtDIACHILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtDIACHILayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtDCHI, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtDIACHILayout.setVerticalGroup(
            txtDIACHILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtDIACHILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDCHI, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        txtGIOITINH.setBackground(new java.awt.Color(204, 204, 204));

        txtGT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGT.setText("jLabel8");

        javax.swing.GroupLayout txtGIOITINHLayout = new javax.swing.GroupLayout(txtGIOITINH);
        txtGIOITINH.setLayout(txtGIOITINHLayout);
        txtGIOITINHLayout.setHorizontalGroup(
            txtGIOITINHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtGIOITINHLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtGT, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtGIOITINHLayout.setVerticalGroup(
            txtGIOITINHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtGIOITINHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGT, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        txtDOIPASSS.setBackground(new java.awt.Color(102, 255, 102));
        txtDOIPASSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDOIPASSSMouseClicked(evt);
            }
        });

        jLabel9.setText("ĐỔI MẬT KHẨU");

        javax.swing.GroupLayout txtDOIPASSSLayout = new javax.swing.GroupLayout(txtDOIPASSS);
        txtDOIPASSS.setLayout(txtDOIPASSSLayout);
        txtDOIPASSSLayout.setHorizontalGroup(
            txtDOIPASSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtDOIPASSSLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        txtDOIPASSSLayout.setVerticalGroup(
            txtDOIPASSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtDOIPASSSLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGIOITINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSODT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTENDANGNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNGAYSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDOIPASSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTENDANGNHAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNGAYSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSODT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGIOITINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)))
                .addGap(41, 41, 41)
                .addComponent(txtDOIPASSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("THÔNG TIN CÁ NHÂN KHÁCH HÀNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDOIPASSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDOIPASSSMouseClicked
        // TODO add your handling code here:
        new DoiPass(u, r).setVisible(true);
        
    }//GEN-LAST:event_txtDOIPASSSMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jpDangxuat;
    private javax.swing.JLabel jpDangxuat1;
    private javax.swing.JLabel jpDangxuat2;
    private javax.swing.JLabel jpDangxuat3;
    private javax.swing.JLabel jpDangxuat4;
    private javax.swing.JLabel jpDangxuat5;
    private javax.swing.JLabel jpDangxuat6;
    private javax.swing.JLabel jpDangxuat7;
    private javax.swing.JLabel jpDangxuat8;
    private javax.swing.JPanel jpDangxuatt;
    private javax.swing.JPanel jpDangxuatt1;
    private javax.swing.JPanel jpDangxuatt2;
    private javax.swing.JPanel jpDangxuatt3;
    private javax.swing.JPanel jpDangxuatt4;
    private javax.swing.JPanel jpDangxuatt5;
    private javax.swing.JPanel jpDangxuatt6;
    private javax.swing.JPanel jpDangxuatt7;
    private javax.swing.JPanel jpDangxuatt8;
    private javax.swing.JLabel txtDCHI;
    private javax.swing.JPanel txtDIACHI;
    private javax.swing.JPanel txtDOIPASSS;
    private javax.swing.JPanel txtGIOITINH;
    private javax.swing.JLabel txtGT;
    private javax.swing.JPanel txtHOTEN;
    private javax.swing.JPanel txtNGAYSINH;
    private javax.swing.JLabel txtNGSINH;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JPanel txtSODT;
    private javax.swing.JLabel txtTEN;
    private javax.swing.JPanel txtTENDANGNHAP;
    private javax.swing.JLabel txtUSE;
    // End of variables declaration//GEN-END:variables

    private void fillTT() {
        if (r.equalsIgnoreCase("KH")) {
            try {
                PreparedStatement ps = cn.prepareStatement("SELECT * FROM KHACHHANG WHERE USENAMES=?");
                ps.setString(1, u);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    txtUSE.setText(rs.getString(1));
                    txtTEN.setText(rs.getString(2));
                    txtNGSINH.setText(rs.getString(3));
                    txtSDT.setText(rs.getString(4));
                    txtDCHI.setText(rs.getString(5));
                    txtGT.setText(rs.getString(6));
                }
            } catch (Exception e) {
            }
        }else if(r.equalsIgnoreCase("ST")){
            try {
                PreparedStatement ps = cn.prepareStatement("SELECT * FROM STYLELIST WHERE USENAMES=?");
                ps.setString(1, u);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    txtUSE.setText(rs.getString(1));
                    txtTEN.setText(rs.getString(2));
                    txtNGSINH.setText(rs.getString(3));
                    txtSDT.setText(rs.getString(4));
                    txtDCHI.setText(rs.getString(5));
                    txtGT.setText(rs.getString(6));
                }
            } catch (Exception e) {
            }
        }else {
            try {
                PreparedStatement ps = cn.prepareStatement("SELECT * FROM NHANVIEN WHERE USENAMES=?");
                ps.setString(1, u);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    txtUSE.setText(rs.getString(1));
                    txtTEN.setText(rs.getString(2));
                    txtNGSINH.setText(rs.getString(3));
                    txtSDT.setText(rs.getString(4));
                    txtDCHI.setText(rs.getString(5));
                    txtGT.setText(rs.getString(6));
                }
            } catch (Exception e) {
            }
        }
    }
}
